### ISSUE TITLE
Overly slow loading times for article lists on home page

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#153]
It takes about 3 seconds to load the lists of "Recently Added" and "Recently Updated" articles on the homepage and about 2 seconds to display lists of articles on search results page. This didn't used to be the case; it started happening sometime in late November 2014 (in case this helps identify the problem).

This is perhaps related to open issue #94 (HTTP keep-alive doesn't seem to be working ), given that load times do seem quicker if you keep repeating the action.

**Comment by alexkyllo** [comment]
I believe the slow loading times are due to table scans on the Article table. The landing page shows the 5 recently created and 5 most recently updated articles, and it has to query all 288,330 articles and sort them in order to do this. Adding indexes on created_at and updated_at columns should fix this.

![screen shot 2015-04-23 at 8 04 20 pm](https://cloud.githubusercontent.com/assets/2609312/7335688/16930654-eb84-11e4-9012-4c33a81e0371.png)

**Comment by alexkyllo** [comment]
Great success! These queries that took 20 seconds previously on my laptop are now instantaneous. Pushed the migration to master and will run it on the production db shortly.

![screen shot 2015-04-25 at 8 02 51 pm](https://cloud.githubusercontent.com/assets/2609312/7335735/8707fa46-eb86-11e4-851f-3e16eb01213e.png)

**Comment by alexkyllo** [comment]
Deployed to production. Reopening this though, because I only addressed the home page. The search results page is hitting elasticsearch, so different steps would need to be taken to speed up search results.

**Comment by eplebel** [comment]
Great, that definitely fixed the problem for the homepage! I created a separate issues for the slow loading times for search results, see
