### ISSUE TITLE
Allow/display carriage returns in comments and hyperlink URLs

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#175]
Currently, if one enters a carriage return to start a new line in a comment, it eliminates it after saving the comment. We need to display such carriage returns so we can not only have new lines, but also empty lines.

Also, we should hyperlink any URLs that are contained in a comment (e.g.
https://www.curatescience.org/beta/#/articles/335218 at the bottom in the general comments)

While you're at it, can you also hyperlink any URLs in abstracts too, thanks!

**Comment by eplebel** [comment]
Multiple lines and hyperlinking text are still not working for:
(1) comments for study components (data&syntax, materials, registration)
(2) general comments below the replication table

Also, hyperlinking text still does not work for abstract (though multiple lines *are* working within abstract text box)

**Comment by alexkyllo** [comment]
I looked at the code for this--it is using regular expressions to detect a URL pattern and then inserting it into an <a> element using string concatenation, which is really not a correct or safe way to allow hyperlinks in user input. As you can see, it is easily broken, and it also could allow users to inject malicious code. It is using m.trust() which flags user input as trusted. This is dangerous, and you can read more about it here: https://lhorie.github.io/mithril/mithril.trust.html

If you really want this feature, the right way to do it is to provide e.g. a Markdown editor (like Github does). 

In the meantime, I would recommend undoing this entire commit https://github.com/ScienceCommons/www/commit/2cd3da25049ab53efd2ffa30b573b1cc7070962b
Let me know if you'd like me to do that.

**Comment by eplebel** [comment]
Thanks for looking into this! 
Quick clarification though: how exactly does automatically hypertexting links in this manner "allow users to inject malicious code"? (I looked through the mithril documentation you linked to, but still don't understand unfortunately).

**Comment by eplebel** [comment]
this is a test: https://www.curatescience.org/beta/#/articles/335262

**Comment by alexkyllo** [comment]
There are libraries that do this, here's one that looks good: https://github.com/gregjacobs/Autolinker.js

It shouldn't take more than an hour or two to add it in and test it.

**Comment by eplebel** [comment]
Nice, that library looks *very* good!

**Comment by alexkyllo** [comment]
See how I as a user can inject javascript into my comments currently:
![screenshot from 2015-07-26 20 29 39](https://cloud.githubusercontent.com/assets/2609312/8898181/1a4ef930-33d5-11e5-9de5-72fff5c64398.png)
The right way to deal with this, if we want to allow hyperlinks in comments, is to do some server-side sanitizing of the HTML, to only whitelist link elements and disallow all other HTML, using this: https://github.com/rails/rails-html-sanitizer

**Comment by eplebel** [comment]
Ah OK I now see how this could be dangerous/unsafe!

**Comment by alexkyllo** [comment]
I just pushed commits to staging, to use Autolinker.js to detect and convert URLs in abstract and comment text, and to sanitize the text on the server side to remove any HTML/CSS/JS besides the allowed 'a' (hyperlink) elements.

Since we're doing the sanitization server-side it's still possible for the user to inject javascript in their own comments locally, but only until they refresh the page. When the comment goes to the server and comes back it will be sanitized, so they can no longer spread malicious code to other users.

**Comment by eplebel** [comment]
Great, that was fast!
One minor thing I just noticed: For the abstract text box, the auto-linking only appears once you refresh the page.

**Comment by eplebel** [comment]
Also, should I log the allow/display carriage returns under a different issue?

**Comment by alexkyllo** [comment]
I'm not quite sure how to make it so that abstract text URL auto-linking shows up without refreshing... I can try but it might take a while to figure it out.

Carriage returns in comments are working for me, do they work for you now? Are you wanting carriage returns in the abstract text too? I can do that as well.

**Comment by eplebel** [comment]
For now, don't worry about the URL not auto-linking for the abstract text box without refreshing, that's a very minor issue compared to several other major open issues.

For carriage returns, the situation is pretty complicated somehow. Carriage returns are working for element-specific comments within the replication table, however they are *not* working for general comments at the bottom of the page. For the abstract text box, carriage returns *are* working once you save the article, but then when you reload the page, the carriage returns disappear somehow. Very strange.

**Comment by alexkyllo** [comment]
This one is complicated because different browsers behave differently. When you hit "Enter" inside of a contentEditable element (like the abstract text box) in Chrome, Safari and IE it will wrap the new line in a <div> element but in Firefox it will insert a <br> element. I got carriage returns in the abstract working in Firefox on my machine but it's still broken in Chrome. I think 'll need to do a little regex or something to find and replace the <div> tags with <br> tags so it works in non-Firefox browsers.

**Comment by eplebel** [comment]
Interesting. However, if carriage returns are working for element-specific comments within the replication table (see my July 27, 2015 comment above), then can't we just use the same "contentEditable element" used within the replication table for the abstract and general comment box?
UPDATE: Oh shoot, I just realized the element used within the replication table is probably **not** a "contentEditable element" given that one can't edit a comment once it's posted (though we'll want this in the future). 
But how does github do it? LOL

Carriage returns are working for element-specific comments within the replication table, however they are not working for general comments at the bottom of the page.

**Comment by alexkyllo** [comment]
Yep, your observation is correct--only the article header info fields are contentEditable elements, the fields in the studies/replications table aren't. HTML contentEditable elements are kind of a new thing and are not completely cross-browser standardized yet. The story is simpler for form inputs and textareas (like what I'm typing this comment in right now) because they've been part of the browser standards much longer.

Anyway, not to worry, I'm confident I can get this issue fixed, just wanted to give you a status update.

**Comment by eplebel** [comment]
So why not just use the older/more standardized "textareas"?

**Comment by alexkyllo** [comment]
Well we could do that, but it'd change the user experience/look-and-feel of the edit mode a bit, and it might actually be more work than just fixing the line break issue at this point. I'll take another look tonight.

**Comment by eplebel** [comment]
Ah OK, that makes sense

**Comment by alexkyllo** [comment]
https://github.com/ScienceCommons/www/pull/46 contains fixes for both this carriage return issue (in abstract text and main study comments) and for the issue you identified this morning (when adding/linking a replication, the replication study is hidden by default instead of being visible).

**Comment by eplebel** [comment]
Awesome, looks like that did the trick!!
