### ISSUE TITLE
beta pages sometimes don't load -- or are excruciatingly slow to load when resuming session

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#220]
i've noticed this before for a while now, but the problem doesn't seem to happen consistently and so i haven't been able to figure out a set of conditions for this to be reproducible. however, here's a screenshot of various error messages that might help troubleshoot the situation:

![503-error](https://cloud.githubusercontent.com/assets/4512335/8761379/f9201244-2d1c-11e5-9003-df03fe63295c.png)

Actually, the critical error is likely the 503 error message, because once things start working again (by just waiting a long time -- or logging out and logging back in, though even this latter strategy doesn't always seem to work), the other two error messages are still being displayed even though the page loads fine (though I guess these two other error messages should also be looked at eventually.)

This might be related to #94 (HTTP keep-alive doesn't seem to be working

**Comment by alexkyllo** [comment]
I noticed this too, and Heroku's docs explain that it's a timeout error, but I don't know the root cause yet. I suspect that this query is just taking too long at times: https://github.com/ScienceCommons/api/blob/master/app/controllers/articles_controller.rb#L41 
I restarted the app through Heroku and that seemed to help, though.

**Comment by eplebel** [comment]
UPDATE: I've now figured out how to make this problem reproducible. If you browse away from the landing page for more than 30 minutes and then go back to it, you get the problem basically every time (or if you're on idle on an article page for more than 30 minutes and then try to browse to landing page, it just hangs forever).

Once you're in this state, there seems to be only 2 ways to get around the problem:
1. Clear your browser's cache, close the page, and then browse back to landing page
2. Initiate a search query, browse to an article page, and then go back to landing page

**Comment by eplebel** [comment]
It's definitely improved to 2-3 seconds, but at least without timing out (though i still want to test a bit more  before closing the issue). 

thanks for the additional info regarding the caching option of the Standard tier; i'll keep that in mind.

**Comment by eplebel** [comment]
The page still seems to take 10+ seconds to load after an extended time of inactivity (i left my laptop on all night and in the morning observed this). However, I will confirm that this is reproducible tomorrow.

**Comment by alexkyllo** [comment]
Minifying main.js cut about 1.5 seconds off the loading time (for me). I just e-mailed you a little more information on that.

**Comment by alexkyllo** [comment]
I haven't seen the 503 gateway timeouts since I optimized the query for the landing page. That also speeded things up quite a bit, and minifying the JS helped too. But I don't think there's much else I can do in the code itself to speed the page load up further, so I think we can consider this issue closed for now.
