### ISSUE TITLE
update signup config variable on splash page to direct subscribers to my mailchimp account

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/api#234]
update signup config variable on splash page to direct subscribers to my mailchimp account rather than Christian's mailchimp account

**Comment by alexkyllo** [comment]
What's the URL for your mailing list?
Here's Christian's, can you give me a similar URL to replace it with?
https://christianbattista.us7.list-manage.com/subscribe/post?u=d140eca9cfe4a96473dac6ea5&id=fba08af7dd

Also, there are two environment variables in Heroku that may need to be changed:
MAILCHIMP_API_KEY
MAILCHIMP_ID
Because this is what controls which mailchimp mailing list populates the beta mailing list section on the admin page https://curatescience-staging.herokuapp.com/beta/#/admin

**Comment by eplebel** [comment]
OK I've generated a new API key for our new Mailchimp account (i've sent you an email with the credentials to log into our Mailchimp account; you can find the API key under the Curate Science account setting [top-right], then "Extras")

The URL for our new mailing list is: 0833383918fc50773891d363a&id=aaad5734e3 (extracted from this string 0833383918fc50773891d363a&amp;id=aaad5734e3)

**Comment by eplebel** [comment]
i just noticed that the form action code for the signup button in the signup section of the alpha page is still the old one, and hence needs to be changed to our new one (see my previous comment)

<div id="mc_embed_signup">
        <form action="https://christianbattista.us7.list-manage.com/subscribe/post?u=d140eca9cfe4a96473dac6ea5&amp;id=fba08af7dd" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate form-search pull-center" target="_blank" novalidate>
